name: CD

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --version ${GITHUB_REF#refs/*/} --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Push To Nuget
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json