name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release